### ISSUE TITLE
Bug 1 in Release 0.1

### ISSUE THREAD

**Issue by himusoni** [ankursuman/Design-lab#1]
**Test case ENTHUSIASTIC-3: Test-3: Manage Entry**
**Test case number 4**

[ENTHUSIASTIC_TEST_REPORT.pdf](https://github.com/ankursuman/Design-lab/files/4807807/ENTHUSIASTIC_TEST_REPORT.pdf)

#4 System is not generating alert message "Invalid Error" when available slot < 0 and available slot > 1000. So this test case is failed. 

Please resolve this test case.

**Comment by ankursuman** [comment]
Resolved
`if(available_slots < 0 and available_slots > 1000):
                print("Invalid Error")
            if(available_slots == 1000):
                print("All slots are available right now ")
            if(available_slots == 0):
                print("No slot is available")`
