### ISSUE TITLE
Bug 2 in Release 0.1

### ISSUE THREAD

**Issue by himusoni** [ankursuman/Design-lab#2]
**Test case ENTHUSIASTIC-3: Test-3: Manage Entry**
**Test case number 17**

[ENTHUSIASTIC_TEST_REPORT.pdf](https://github.com/ankursuman/Design-lab/files/4807807/ENTHUSIASTIC_TEST_REPORT.pdf)

#17  System is generating incorrect result. It is not handling #17 test case and not getting expected output result message "Your payment is unsuccessful".

Please resolve this test case.

**Comment by ankursuman** [comment]
Resolved
`if payment_status:
                    print("gate opened")
                    time.sleep(3)
                    print("gate closed")
                    slot_no = veichle_slot_list[car_plate]
                    object2.slot_list[slot_no] = False
                    count = object2.update_available_slot(False)
                    print("Current available slots is {}".format(count))
                else:
                    print("Payment unsuccessfull")`
